name: push

on:
  push:
    branches: [ "master" ]

jobs:
  fcm:
    runs-on: [self-hosted]

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: push commit
        run: git push
      - name: migrate Database
        run: php artisan migrate
      - name: Execute tests
        run: php artisan test
